---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "whoami.selectorLabels" . | nindent 4 }}
{{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
{{- if not (empty .Values.service.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ quote . }}
  {{- end }}
{{- end }}